//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Esempio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodotto
    {
        public int Codice { get; set; }
        public string Denominazione { get; set; }
        public string Descrizione { get; set; }
        public double Prezzo { get; set; }
        public int Giacenza { get; set; }
        public Nullable<bool> Visibile { get; set; }
        public Nullable<bool> Nuovo { get; set; }
    }
}
